export interface TemplateFile {
  path: string;
  content: string;
}

export function createQuickstartTemplateFiles(projectName: string): TemplateFile[] {
  return [
    {
      path: 'package.json',
      content: `${JSON.stringify({
        name: projectName,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          doctor: 'linnkit doctor',
          start: 'linnkit run hello --input "你好，介绍一下你自己"',
        },
        dependencies: {
          '@linnlabs/linnkit': '^0.8.0',
          zod: '^3.22.0',
        },
        devDependencies: {},
      }, null, 2)}\n`,
    },
    {
      path: '.env.example',
      content: [
        'OPENAI_API_KEY=',
        'OPENAI_BASE_URL=https://api.openai.com/v1',
        'OPENAI_MODEL=gpt-4.1-mini',
        '',
      ].join('\n'),
    },
    {
      path: 'agents/hello.mjs',
      content: [
        "import { defineAgent } from '@linnlabs/linnkit';",
        '',
        'export const helloAgent = defineAgent({',
        "  id: 'hello',",
        "  version: '0.1.0',",
        "  description: 'A tiny hello-world linnkit agent.',",
        "  modelId: process.env.OPENAI_MODEL || 'gpt-4.1-mini',",
        "  systemPrompt: 'You are a concise, warm assistant. Reply in the same language as the user.',",
        '  tools: [],',
        '  contextPolicy: {',
        "    profileId: 'agent',",
        '    contextTrace: { enabled: true },',
        '  },',
        '});',
        '',
      ].join('\n'),
    },
    {
      path: 'adapters/openai-compatible.mjs',
      content: [
        'function readContentDelta(choice) {',
        '  const delta = choice?.delta;',
        "  if (typeof delta?.content === 'string') return delta.content;",
        "  if (typeof choice?.message?.content === 'string') return choice.message.content;",
        "  return '';",
        '}',
        '',
        'function normalizeMessages(messages) {',
        '  return messages.map((message) => {',
        "    if (message.role === 'tool') {",
        "      return { role: 'tool', tool_call_id: message.tool_call_id, content: String(message.content ?? '') };",
        '    }',
        "    return { role: message.role, content: String(message.content ?? '') };",
        '  });',
        '}',
        '',
        'export function createOpenAICompatibleProvider(options = {}) {',
        '  const apiKey = options.apiKey ?? process.env.OPENAI_API_KEY;',
        "  const baseUrl = (options.baseUrl ?? process.env.OPENAI_BASE_URL ?? 'https://api.openai.com/v1').replace(/\\/$/, '');",
        '',
        '  async function request(modelId, messages, callOptions = {}, stream = false) {',
        '    if (!apiKey) {',
        "      throw new Error('Missing OPENAI_API_KEY. Copy .env.example to .env or export OPENAI_API_KEY.');",
        '    }',
        `    const response = await fetch(\`\${baseUrl}/chat/completions\`, {`,
        "      method: 'POST',",
        '      headers: {',
        "        'content-type': 'application/json',",
        '        authorization: `Bearer ${apiKey}`,',
        '      },',
        '      body: JSON.stringify({',
        '        model: modelId,',
        '        messages: normalizeMessages(messages),',
        '        stream,',
        '        tools: callOptions.tools,',
        '        tool_choice: callOptions.tool_choice,',
        '        temperature: callOptions.temperature,',
        '        max_tokens: callOptions.max_tokens,',
        '        stream_options: stream ? callOptions.stream_options : undefined,',
        '      }),',
        '      signal: callOptions.signal,',
        '    });',
        '',
        '    if (!response.ok) {',
        '      const detail = await response.text();',
        '      throw new Error(`LLM request failed: ${response.status} ${detail}`);',
        '    }',
        '    return response;',
        '  }',
        '',
        '  return {',
        '    async chatCompletion(modelId, messages, callOptions = {}) {',
        '      const response = await request(modelId, messages, callOptions, false);',
        '      const json = await response.json();',
        '      const choice = json.choices?.[0];',
        '      return {',
        '        content: choice?.message?.content ?? \'\',',
        '        tool_calls: choice?.message?.tool_calls,',
        '        usage: json.usage,',
        '      };',
        '    },',
        '',
        '    async chatCompletionStream(modelId, messages, callOptions = {}, onContent, onError, onFinish, _onThought, onUsage) {',
        '      try {',
        '        const response = await request(modelId, messages, callOptions, true);',
        '        if (!response.body) throw new Error(\'Streaming response body is empty.\');',
        '        const reader = response.body.getReader();',
        '        const decoder = new TextDecoder();',
        "        let buffer = '';",
        '',
        '        while (true) {',
        '          const { done, value } = await reader.read();',
        '          if (done) break;',
        '          buffer += decoder.decode(value, { stream: true });',
        "          const lines = buffer.split('\\n');",
        '          buffer = lines.pop() ?? \'\';',
        '',
        '          for (const rawLine of lines) {',
        '            const line = rawLine.trim();',
        "            if (!line || !line.startsWith('data:')) continue;",
        "            const payload = line.slice('data:'.length).trim();",
        "            if (payload === '[DONE]') {",
        "              onFinish?.('stop');",
        '              return;',
        '            }',
        '            const parsed = JSON.parse(payload);',
        '            if (parsed.usage) onUsage?.(parsed.usage);',
        '            const choice = parsed.choices?.[0];',
        '            const content = readContentDelta(choice);',
        '            if (content) onContent?.(content);',
        '            if (choice?.finish_reason) onFinish?.(choice.finish_reason);',
        '          }',
        '        }',
        "        onFinish?.('stop');",
        '      } catch (error) {',
        '        onError?.(error instanceof Error ? error : new Error(String(error)));',
        '      }',
        '    },',
        '  };',
        '}',
        '',
      ].join('\n'),
    },
    {
      path: 'linnkit.config.mjs',
      content: [
        "import { defineConfig } from '@linnlabs/linnkit';",
        "import { helloAgent } from './agents/hello.mjs';",
        "import { createOpenAICompatibleProvider } from './adapters/openai-compatible.mjs';",
        '',
        'export default defineConfig({',
        '  agents: [helloAgent],',
        '  defaultModelId: process.env.OPENAI_MODEL || helloAgent.modelId,',
        '  llm: () => createOpenAICompatibleProvider(),',
        '});',
        '',
      ].join('\n'),
    },
    {
      path: 'README.md',
      content: [
        `# ${projectName}`,
        '',
        'A minimal linnkit quickstart project.',
        '',
        '```bash',
        'cp .env.example .env',
        'npm install',
        'export OPENAI_API_KEY=...',
        'npx linnkit doctor',
        'npx linnkit run hello --input "你好"',
        '```',
        '',
      ].join('\n'),
    },
  ];
}
